name: CMake Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CXX_STANDARD: 17

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: ./build
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_CXX_STANDARD=${{ env.CXX_STANDARD }}

    - name: Build project
      working-directory: ./build
      run: cmake --build . --config ${{ env.BUILD_TYPE }}

    - name: Run tests
      working-directory: ./build
      run: |
        echo "Testing equation solver:"
        OUTPUT=$(./solver_application/solve <<< "1 -3 2")
        echo "$OUTPUT"
        echo "$OUTPUT" | grep -q "x1 = 1.000000"
        echo "$OUTPUT" | grep -q "x2 = 2.000000"
